name: soporte_app
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.0-266.0.dev <4.0.0"

dependencies:
  calendar_date_picker2: ^0.5.2
  flutter:
    sdk: flutter
  path_provider: ^2.0.15
  pdf: ^3.10.1
  pocketbase: ^0.8.0
  printing: ^5.10.3
  provider: ^6.0.5
  url_launcher: ^6.1.10
  window_manager: ^0.3.1

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
